const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='brutusmaq_orcamento_profissional_v2';
let state={items:[],images:{}};
const fieldIds=['quoteNumber','quoteDate','validity','responsible','clientName','clientDoc','clientPhone','clientEmail','machineName','application','solution','scopeSummary','model','power','workArea','production','voltage','material','discount','freightValue','delivery','payment','freightCondition','installation','warranty','support','notes'];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function val(id){return $('#'+id)?.value||''}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function uid(){return 'i'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function addItem(data={}){state.items.push({id:uid(),code:data.code||String(state.items.length+1).padStart(2,'0'),description:data.description||'',qty:Number(data.qty??1),unit:Number(data.unit??0)});renderItems();renderPreview();autosave()}
function removeItem(id){state.items=state.items.filter(x=>x.id!==id);renderItems();renderPreview();autosave()}
function renderItems(){const root=$('#itemEditor');root.innerHTML=state.items.map((it,i)=>`<div class="item-card" data-id="${it.id}"><div class="item-card-head"><strong>Item ${i+1}</strong><button class="remove-item" data-remove="${it.id}">Remover</button></div><div class="item-grid"><label>Código<input data-k="code" value="${esc(it.code)}"></label><label>Descrição<input data-k="description" value="${esc(it.description)}" placeholder="Descrição do equipamento ou acessório"></label><label>Qtd.<input data-k="qty" type="number" min="0" step="1" value="${it.qty}"></label><label>Valor unitário<input data-k="unit" type="number" min="0" step="0.01" value="${it.unit}"></label></div></div>`).join('');
 $$('[data-remove]',root).forEach(b=>b.onclick=()=>removeItem(b.dataset.remove));
 $$('[data-k]',root).forEach(inp=>inp.oninput=()=>{const item=state.items.find(x=>x.id===inp.closest('.item-card').dataset.id);if(!item)return;item[inp.dataset.k]=['qty','unit'].includes(inp.dataset.k)?Number(inp.value||0):inp.value;renderPreview();autosave()});
}
function totalData(){const subtotal=state.items.reduce((s,x)=>s+(Number(x.qty)||0)*(Number(x.unit)||0),0),discount=Number(val('discount')||0),freight=Number(val('freightValue')||0),total=Math.max(0,subtotal-discount+freight);return{subtotal,discount,freight,total}}
function imageHTML(id,cls=''){const src=state.images[id];return `<div class="image-frame ${cls} ${src?'':'empty'}">${src?`<img src="${src}" alt="Foto do equipamento">`:''}</div>`}
function footer(n){return `<footer class="doc-footer"><strong>BRUTUSMAQ INDÚSTRIA E COMÉRCIO DE MÁQUINAS LTDA.</strong><span>CNPJ 36.094.320/0001-03 | Contenda/PR</span><span>Página ${n} de 3</span></footer>`}
function header(title,sub){return `<header class="doc-header"><div class="doc-brand"><img src="assets/logo-b.png" alt="B"><div><div class="doc-brand-name">BRUTUSMAQ</div><div class="doc-brand-tag">FORÇA QUE TRANSFORMA</div></div></div><div class="doc-title"><h1>${title}</h1><p>${sub}</p></div></header>`}
function renderPreview(){const t=totalData();const rows=state.items.length?state.items.map((x,i)=>`<tr><td>${esc(x.code||String(i+1).padStart(2,'0'))}</td><td>${esc(x.description)}</td><td class="right">${x.qty}</td><td class="right">${money(x.unit)}</td><td class="right"><b>${money(x.qty*x.unit)}</b></td></tr>`).join(''):`<tr><td colspan="5">Nenhum item adicionado.</td></tr>`;
 $('#documentPreview').innerHTML=`
 <section class="doc-page">${header('ORÇAMENTO COMERCIAL','Proposta profissional de equipamento industrial')}<div class="doc-body"><div class="eyebrow">PROPOSTA COMERCIAL</div><div class="machine-name">${esc(val('machineName')||'EQUIPAMENTO INDUSTRIAL')}</div><div class="meta"><div class="meta-cell"><span>ORÇAMENTO Nº</span><strong>${esc(val('quoteNumber'))}</strong></div><div class="meta-cell"><span>DATA</span><strong>${formatDate(val('quoteDate'))}</strong></div><div class="meta-cell"><span>VALIDADE</span><strong>${esc(val('validity'))}</strong></div><div class="meta-cell"><span>RESPONSÁVEL</span><strong>${esc(val('responsible'))}</strong></div></div><div class="client-strip"><div><span>CLIENTE / EMPRESA</span><strong>${esc(val('clientName'))}</strong></div><div><span>CNPJ / CPF</span><strong>${esc(val('clientDoc'))}</strong></div><div><span>CONTATO</span><strong>${esc(val('clientPhone'))}</strong></div></div>${imageHTML('heroImage','hero')}<div class="proposal-grid"><div class="doc-section"><h2>SOLUÇÃO PROPOSTA</h2><div class="doc-text">${esc(val('solution'))}</div></div><aside class="investment"><span>INVESTIMENTO TOTAL</span><strong>${money(t.total)}</strong><small>Condições comerciais detalhadas na página 3.</small></aside></div><div class="scope"><span>ESCOPO RESUMIDO</span><div class="doc-text">${esc(val('scopeSummary'))}</div></div></div>${footer(1)}</section>
 <section class="doc-page">${header('EQUIPAMENTO OFERTADO','Fotos, aplicação e especificações principais')}<div class="doc-body"><div class="gallery">${imageHTML('gallery1')}<div class="gallery-side">${imageHTML('gallery2')}${imageHTML('gallery3')}</div></div><div class="doc-section"><h2>APLICAÇÃO</h2><div class="doc-text">${esc(val('application'))}</div></div><div class="doc-section"><h2>ESPECIFICAÇÕES PRINCIPAIS</h2><div class="specs">${[['MODELO','model'],['POTÊNCIA','power'],['ÁREA DE TRABALHO','workArea'],['PRODUÇÃO','production'],['ALIMENTAÇÃO','voltage'],['MATERIAL PRINCIPAL','material']].map(([a,b])=>`<div class="spec"><span>${a}</span><strong>${esc(val(b))}</strong></div>`).join('')}</div></div><div class="doc-section"><h2>ITENS INCLUSOS</h2><table class="items-table"><thead><tr><th>ITEM</th><th>DESCRIÇÃO</th><th class="right">QTD.</th><th class="right">VALOR UNIT.</th><th class="right">TOTAL</th></tr></thead><tbody>${rows}</tbody></table></div><div class="differentials"><b>DIFERENCIAIS</b> &nbsp; ✓ Construção robusta &nbsp; ✓ Manutenção simplificada &nbsp; ✓ Assistência técnica BRUTUSMAQ</div></div>${footer(2)}</section>
 <section class="doc-page">${header('CONDIÇÕES COMERCIAIS','Informações finais para fechamento da proposta')}<div class="doc-body"><div class="total-banner"><span>VALOR TOTAL DA PROPOSTA</span><strong>${money(t.total)}</strong></div><div class="commercial">${[['PRAZO DE FABRICAÇÃO / ENTREGA','delivery'],['FORMA DE PAGAMENTO','payment'],['FRETE','freightCondition'],['INSTALAÇÃO / COMISSIONAMENTO','installation'],['GARANTIA','warranty'],['ASSISTÊNCIA TÉCNICA','support']].map(([a,b])=>`<div class="commercial-card"><span>${a}</span><p>${esc(val(b))}</p></div>`).join('')}</div><div class="summary-values"><div class="sum-card"><span>SUBTOTAL</span><strong>${money(t.subtotal)}</strong></div><div class="sum-card"><span>DESCONTO</span><strong>${money(t.discount)}</strong></div><div class="sum-card"><span>FRETE</span><strong>${money(t.freight)}</strong></div><div class="sum-card final"><span>TOTAL FINAL</span><strong>${money(t.total)}</strong></div></div><div class="doc-section"><h2>OBSERVAÇÕES COMERCIAIS</h2><div class="doc-text">${esc(val('notes'))}</div></div><div class="approval"><div class="doc-section"><h2>APROVAÇÃO DO CLIENTE</h2></div><div class="approval-grid"><div class="signature">NOME / EMPRESA</div><div class="signature">CNPJ / CPF</div><div class="signature">DATA</div><div class="signature">ASSINATURA / ACEITE</div></div></div></div>${footer(3)}</section>`;
}
function formatDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function collect(){const fields={};fieldIds.forEach(id=>fields[id]=val(id));return{version:2,fields,items:state.items,images:state.images,savedAt:new Date().toISOString()}}
function apply(data){Object.entries(data.fields||{}).forEach(([id,v])=>{const e=$('#'+id);if(e)e.value=v});state.items=Array.isArray(data.items)?data.items:[];state.images=data.images||{};renderItems();renderPreview()}
function autosave(){clearTimeout(autosave.t);autosave.t=setTimeout(()=>{try{localStorage.setItem(STORE,JSON.stringify(collect()))}catch(e){}},400)}
function save(){try{localStorage.setItem(STORE,JSON.stringify(collect()));toast('Orçamento salvo neste navegador.')}catch(e){toast('Não foi possível salvar. Reduza o tamanho das imagens.')}}
function exportData(){const blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`orcamento-${val('quoteNumber')||'brutusmaq'}.json`;a.click();URL.revokeObjectURL(a.href)}
function reset(){if(!confirm('Criar um novo orçamento e limpar o atual?'))return;localStorage.removeItem(STORE);location.reload()}
function compressImage(file,cb){const img=new Image(),r=new FileReader();r.onload=()=>img.src=r.result;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.84))};r.readAsDataURL(file)}
$$('.section-toggle').forEach(b=>b.onclick=()=>{const s=b.closest('.editor-section');s.classList.toggle('open');$('b',b).textContent=s.classList.contains('open')?'−':'+'});
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#workspace').className='workspace '+b.dataset.view});
fieldIds.forEach(id=>$('#'+id)?.addEventListener('input',()=>{renderPreview();autosave()}));
$$('input[type=file][data-image]').forEach(inp=>inp.onchange=()=>{const f=inp.files[0];if(!f)return;compressImage(f,src=>{state.images[inp.dataset.image]=src;renderPreview();autosave();toast('Foto atualizada.')})});
$('#addItemBtn').onclick=()=>addItem();$('#saveBtn').onclick=save;$('#newBtn').onclick=reset;$('#exportBtn').onclick=exportData;$('#pdfBtn').onclick=()=>{renderPreview();window.print()};
$('#importInput').onchange=()=>{const f=$('#importInput').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{apply(JSON.parse(r.result));save();toast('Dados importados.')}catch(e){toast('Arquivo inválido.')}};r.readAsText(f)};
if(!val('quoteDate'))$('#quoteDate').value=new Date().toISOString().slice(0,10);
try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved)apply(saved);else{addItem({description:'Equipamento principal',qty:1,unit:0});addItem({description:'Acessório incluso',qty:1,unit:0})}}catch(e){addItem({description:'Equipamento principal',qty:1,unit:0})}
renderPreview();
